# .github/workflows/main.yml

name: CI/CD Pipeline for Node.js App

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    # The type of virtual machine the job will run on
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out your repository code so the workflow can access it
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub using the secrets we stored
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Build the Docker image and push it to Docker Hub
    - name: Build and push Docker image
      uses: docker/build-and-push-action@v4
      with:
        context: .
        push: true
        tags: dimpal546/my-devops-project:latest